theme: jekyll-theme-leap-day
title: Result Library BOM
description: Bill of Materials for Result libraries
current_version: 1.0.4.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-bom
  - result-catalog
